#
dev: false

name: Demo Slot Admin Panel

description: Panel admin untuk mengatur saldo demo slot

poster: /assets/images/dafftube.png

avatar: /assets/images/logo_img.png

disqus:

google_analytics: 

url: http://xoilack.github.io/MenolakMaxwin/

baseurl: ""

permalink: /:title

version: v1.0.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

# Admin Credentials (Ubah sesuai keinginan)
ADMIN_USERNAME: admin
ADMIN_PASSWORD_HASH: bee5688aea66a47460b19c76f8f199c6b9585eb726f8322b1429793863609ca2 # SHA256 dari "password"

# Firebase Config (Ganti dengan config asli Anda)
API_KEY: AIzaSyC8t5BHqXv24QZced_CIPjPmkMIYeJxpso
AUTH_DOMAIN: fir-763d5.firebaseapp.com
DATABASE_URL: https://fir-763d5-default-rtdb.firebaseio.com/
PROJECT_ID: fir-763d5
STORAGE_BUCKET: fir-763d5.firebasestorage.app
SENDER_ID: 426798891929
APP_ID: 1:426798891929:web:02383a7f9807f783054908

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  
